FROM ruby:4.0.7-alpine@sha256:1ca7cb33e970630d571e0da6140e0bc925faec8f1f8f51f9f2cdf5e5f5eed7c9

# Installation path
ENV HOME=/app
WORKDIR $HOME

RUN set -ex && \
  adduser -h $HOME -s /bin/false -D -S -G root ruby && \
  chmod g+w $HOME && \
  apk add --update --no-cache make gcc libc-dev git

RUN gem install bundler -v 1.17.3
COPY Gemfile pact-message.gemspec $HOME/
COPY lib/pact/message/version.rb $HOME/lib/pact/message/version.rb
RUN bundle install --no-cache
